movies/urls.py
from django.conf.urls import url

from . import views

app_name = 'movies'

urlpatterns = [
	url(r'^$', views.index, name="index"),
	url(r'^(?P<film_id>[0-9]+)/$', views.EArticleView.as_view(), name='film2'),
    url(r'^comment2/(?P<film_id>[0-9]+)/$', views.add_comment, name='add_comment2'),
]

mysite2/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^movies/', include('movies.urls')),
    url(r'^admin/', admin.site.urls),
]

movies/models.py
from datetime import datetime
from django.db import models
from django.utils import timezone
from treebeard.mp_tree import MP_Node

from django.contrib.postgres.fields import ArrayField

class Genre(models.Model):
	genre_name = models.CharField(max_length=100)

	def __str__(self):
		return self.genre_name

class Country(models.Model):
	country_name = models.CharField(max_length=100)

	def __str__(self):
		return self.country_name

class Film(models.Model):
	film_name = models.CharField(max_length=200)
	genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
	year_of_issue = models.DateField()
	country = models.ForeignKey(Country, on_delete=models.CASCADE)
	producer = models.CharField(max_length=200)
	pub_date = models.DateField('date published', default=datetime.now)
	cast = models.TextField()

	def __str__(self):
		return self.film_name

class Comment(MP_Node):
	film = models.ForeignKey(Film)
	author = models.CharField(max_length=100)
	text = models.TextField()
	pub_date = models.DateTimeField('date published', default=datetime.now)

	node_order_by = ['author']

	def __str__(self):
		return self.author

class Comment2(models.Model):
	path = ArrayField(models.IntegerField())
	film_id = models.ForeignKey(Film)
	author = models.CharField(max_length=100)
	content = models.TextField('Комментарий')
	pub_date = models.DateTimeField('Дата комментария', default=datetime.now)

	def __str__(self):
		return self.content[0:200]

	def get_offset(self):
		level = len(self.path) - 1
		if level > 5:
			level = 5
		return level

	def get_col(self):
		level = len(self.path) - 1
		if level > 5:
			level = 5
		return 12 - level

movies/forms.py
from django import forms
 
from .models import Comment2
 
 
class Comment2Form(forms.Form):
 
    parent_comment = forms.IntegerField(
        widget=forms.HiddenInput,
        required=False
    )

    author = forms.CharField(
    	label="Автор",
    	widget=forms.TextInput
    )
 
    comment_area = forms.CharField(
        label="",
        widget=forms.Textarea
    )

movies/views.py
from django.views import View
from django.shortcuts import render, get_list_or_404, redirect, get_object_or_404, render_to_response
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import RequestContext
from .models import Comment, Film, Comment2
from django.utils import timezone

from django.views.decorators.http import require_http_methods

from .forms import Comment2Form

from django.template.context_processors import csrf

from django.core.exceptions import ObjectDoesNotExist

def index(request):
	context = {'films': Film.objects.all()}
	return render(request, 'movies/index.html', context)

class EArticleView(View):
    template_name = 'movies/film2.html'
    comment_form = Comment2Form
 
    def get(self, request, *args, **kwargs):
        film = get_object_or_404(Film, id=self.kwargs['film_id'])
        context = {}
        context.update(csrf(request))
        user = "y"
        context['film'] = film
        context['comments'] = film.comment2_set.all().order_by('path')

        context['form'] = self.comment_form
 
        return render_to_response(template_name=self.template_name, context=context)
 
@require_http_methods(["POST"])
def add_comment(request, film_id):
 
    form = Comment2Form(request.POST)
    film = get_object_or_404(Film, id=film_id)
 
    if form.is_valid():
        comment = Comment2()
        comment.path = []
        comment.film_id = film
        comment.author = form.cleaned_data['author']
        comment.content = form.cleaned_data['comment_area']
        comment.save()
 
        try:
            comment.path.extend(Comment2.objects.get(id=form.cleaned_data['parent_comment']).path)
            comment.path.append(comment.id)
        except ObjectDoesNotExist:
            comment.path.append(comment.id)
 
        comment.save()
 
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

movies/templates/movies/detail.html
{% load bootstrap3 %}

movies/templates/movies/film2.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>{{ film.film_name }}</title>
    <script type="text/javascript" src="{% static 'movies/jquery-3.2.1.js' %}"></script>
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <script type="text/javascript" src="{% static 'movies/comment.js' %}"></script>
</head>
<body style="padding-top: 20px; padding-bottom: 20px;">
<div class="container">
    <div class="row">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'movies:index' %}">Main</a>
                </div>
            </div>
        </nav>
        <div class="panel panel-default">
            <div class="panel-body">
                <label>Наименование: {{ film.film_name }}</label><br>
                <label>Жанр: {{ film.genre }}</label><br>
                <label>Год выпуска: {{ film.year_of_issue }}</label><br>
                <label>Страна: {{ film.country }}</label><br>
                <label>Режиссер: {{ film.producer }}</label><br>
                <label>Дата выхода: {{ film.pub_date }}</label><br>
                <label>Актерский состав: {{ film.cast }}</label>
            </div>
        </div>
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <h4>Комментарии:</h4>
                {% for comment in comments %}
                    <a name="comment-{{ comment.id }}"></a>
                    <div class="row" id="{{ comment.id }}">
                        <div class="col-md-{{ comment.get_col }} col-md-offset-{{ comment.get_offset }}">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <strong>{{ comment.author }}</strong>&nbsp;&nbsp;
                                    {{ comment.pub_date }}
                                    <a href="#comment-{{ comment.id }}">#</a>
                                </div>
                                <div class="panel-body">
                                    <div>{{ comment.content|safe }}</div>
                                    {% if form %}<a class="btn btn-default btn-xs pull-right"
                                                    onclick="return show_comments_form({{ comment.id }})">
                                        {% bootstrap_icon "share-alt" %}&nbsp;&nbsp;Ответить</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                    <h3 id="write_comment"><a onclick="return show_comments_form('write_comment')">Написать комментарий</a></h3>
                    <form id="comment_form" action="{% url 'movies:add_comment2' 1 %}" method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    {% buttons %}
                        <button type="submit" class="btn btn-primary">{% bootstrap_icon "comment" %}&nbsp;&nbsp;Комментировать</button>
                    {% endbuttons %}
                    </form>
            </div>
            <div class="col-md-2"></div>
    </div>
</div>
</body>
</html>

movies/templates/movies/index.html
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% bootstrap_messages %}

<!DOCTYPE html>
<html>
<head>
	<title>Список фильмов</title>
</head>
<body style="padding-top: 20px; padding-bottom: 20px;">
<div class="container">
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<a class="navbar-brand" href="{% url 'movies:index' %}">Main</a>
			</div>
		</div>
	</nav>
	<div class="panel panel-default">
	<div class="panel-body">
		<h4>Список фильмов</h4>
		<ul>
		{% for film in films %}
			<li><a href="{% url 'movies:film2' film.id %}">{{ film.film_name }}</a></li>
		{% endfor %}
		</ul>
	</div>
</div>
</div>
</body>
</html>